### ISSUE TITLE
Register handler to :logger instead of :error_logger 

### ISSUE THREAD

**Issue by quinnmccourt** [revelrylabs/rollbax#1]
We recently upgraded to Elixir 1.15 and noticed that certain errors like LiveView process crashes were no longer being sent to Rollbar despite having enable_crash_reports enabled. The problem appears to be related to the fact that [Rollbax registers itself as a handler to the old :error_logger](https://github.com/ForzaElixir/rollbax/blob/5ea0ab4850d9ca5ba23ca961344ae6db586a6295/lib/rollbax.ex#L86-L90), while [Elixir has been moving to :logger](https://github.com/elixir-lang/elixir/commit/a7c74e254565242f6ecdf14ee1ae0f7ec231139c) instead.

There's a little more background and discussion in this issue: https://github.com/elixir-lang/elixir/issues/13030

**Comment by quinnmccourt** [comment]
Copy of issue opened by @grossvogel on the main repo https://github.com/ForzaElixir/rollbax/issues/126

**Comment by grossvogel** [comment]
@quinnmccourt is there anything I can do to help this to move forward? Happy to pair up and experiment / troubleshoot / gameplan anytime!

**Comment by quinnmccourt** [comment]
@grossvogel yes, I pivoted over to helping move some peerbot tix forward, but was planning on picking this back up once I had made some progress

**Comment by quinnmccourt** [comment]
putting this back in implement

**Comment by quinnmccourt** [comment]
Picking this back up, have a working branch on `1-use-logger` which mostly includes me just poking around trying stuff to see what happens, going to start just reading through docs again to wrap my head around the whole thing

**Comment by quinnmccourt** [comment]
EOD: continuing grokking logger, going to create a summary of my knowledge tomorrow and reach out for some pairing to rubber duck on some thoughts.

**Comment by stuartjohnpage** [comment]
@grossvogel and I had a chat about this today!

Jason picked this up for a bit when Quinn put it down, and made some great progress in this branch:

[jdp-logger-experiments](https://github.com/revelrylabs/rollbax/tree/jdp-logger-experiments)

He built up a new module which uses the `Logger` module rather than `:error_logger`. The key is a new module, `LoggerHandler`, which replaces the `gen_event` behaviour implementing module, `Logger`.

All the tests are passing, and new ones have been added. All that remains is:

- Making sure there are no edge cases that have been missed
- General clean up - such as cleaning up the `mix.exs` file, improving all the documentation, ensuring best practices, etc.
- Testing out with a low-stakes application - my suggestion would be `rev_time`, because that application hasn't even sent anything to rollbar in months(!) and it's fairly low-stakes

honestly, this is a pretty amazing effort. I found the code to be fairly impenetrable. Jason rocks!!!

**Comment by stuartjohnpage** [comment]
@grossvogel some notes for when you're next around!

- I talked to @nschello, and I think the polite thing to do first time around is open up a PR to the original repo. I'm sure lots of people are interested in this, and he pointed out that they might want this too (I just wanted to open up a new open source repo 😈 )
- I set-up a test site and used a Rollbar api key to start trying to cause error events. It seems errors sent from Plug have an extra layer of nesting which I had to take care of - but after that, all the events came through as expected!
- I've updated the documentation with my own understanding of what's going on (which meant I had to actually figure out what was going -  I now have a pretty good handle (🤞 )) on it.
- I went ahead and bumped up all the dependancies, which required a slight change to one of the `test_helpers`
- I think the next step is to
  - a) wire it up to something: I'd suggest rev_time, as above
  - b) open up a PR to the forzaelixir main repo - I'd be obliged if you and @quinnmccourt  could take a poke around oin `master` on our fork, and walk through the documentation, and give me some general areas of improvement so I can open a final PR
  - c) I was also thinking (typically, on a Friday after it happened) that this could be an ideal candidate for the next TAEFAW 
  - d) if b fails, open up an issue to make this an official ™️  Revelry Open Source project

**Comment by grossvogel** [comment]
@stuartjohnpage thanks, great work on this! I'll make some time to review the changes and documentation carefully again this week. In the meantime, the earlier we wire it up to RevTime the more of a chance we get to confirm it's working 👍

**Comment by stuartjohnpage** [comment]
I shall wire it up to RevTime post-haste!

**Comment by stuartjohnpage** [comment]
Looking good, when running locally with the `dev` access token. Otherwise, I don't know how to trigger an error in staging 😂 

![image](https://github.com/user-attachments/assets/03ce2e78-eeea-485e-aab6-19965a948638)

**Comment by stuartjohnpage** [comment]
Opened up a PR over here: https://github.com/ForzaElixir/rollbax/pull/127

**Comment by stuartjohnpage** [comment]
Final thoughts (for now):

I think we should leave up the PR to the main forza elixir repo for a spell - let's call it a month? We are waiting to see if the maintainers respond to our request to take over maintenance, or if they decide to merge it, or whatever.

So that leaves us until 26/08/2024. After that date, we should look at transforming what we have into our own open source repo, and launching it on Hex

**Comment by nschello** [comment]
@stuartjohnpage I moved this to QA is that appropriate you think?

**Comment by stuartjohnpage** [comment]
for sure!
